### ISSUE TITLE
Provide interfaces for PROs classes

### ISSUE THREAD

**Issue by Kohlroulade** [Esri/arcgis-pro-sdk#2]
As already mentioned within DevSummit in Berlin yesterday I want to share a question here. I´m used to develop against interfaces from ArcObjects to enable unit-testing. This provides mocking and other fake-strategies. However on ArcGIS Pro many functions and properties are static (e.g the GeometryEngine-class). Furthermore the classes themeselfes do not implement any interfaces making it nearly impossible to fake them within unit-tests. 

I wonder if is desired behaviour and strategy and if so how to overcome this to enable unit-testing.

**Comment by a-jaeger** [comment]
I would appreciate a better API for testing purposes - or a guide, how to fake the existing classes. There are a lot of static methods, nearly no interface: a horror for people that use coded testing and test driven development.
