### ISSUE TITLE
How to use fieldmapping in pro sdk

### ISSUE THREAD

**Issue by shenchen1987** [Esri/arcgis-pro-sdk#25]
When I use GPTool "management.Append"，I need fieldmapping as parameter，But I don‘t know how to construct "fieldmapping "? 
code like:
 var  fieldmapping = ????
 var args = Geoprocessing.MakeValueArray(in_data, out_data, "TEST",fieldmapping);
 var result = await Geoprocessing.ExecuteToolAsync("management.Append", args);

**Comment by UmaHarano** [comment]
Hi
Please post this question to the GeoNet community here: https://community.esri.com/groups/arcgis-pro-sdk
Thanks
Uma
