### ISSUE TITLE
Two small errors in ProConcepts-Content-and-Items wiki page

### ISSUE THREAD

**Issue by jg76379** [Esri/arcgis-pro-sdk#26]
A couple of small errors in the code examples on the ProConcepts-Content-and-Items, under the [portal-items section](https://github.com/Esri/arcgis-pro-sdk/wiki/ProConcepts-Content-and-Items#portal-items):

> Execute a query to retrieve all web maps visible to the user, within his or her organization:

```
 //assume signed on user is a member of an organization...
 //get the organization id
 var portalInfo = await portal.GetPortalInfoAsync();
 var orgid = orgid = portalInfo.OrganizationId;

 var query = PortalQueryParameters.CreateForItemsOfType(PortalItemType.WebMap);
 query.Limit = 100;
 query.OrganizationId = orgid;
 //query the organization for web maps...
 PortalQueryResultSet<PortalItem> results = await portal.SearchForContentAsync(query);
 
 //create a map (in Pro) from the first item
 var result = results.First();
 QueuedTask.Run(() => {
    if (MapFactory.Instance.CanCreateMapFrom(result))
        MapFactory.Instance.CreateMapFromItem(result);
    ...
```

The errors:

1. 4th line in the code above, the declaration of the `orgid` variable has an extra `orgid =`

2. The line `var result = results.First();` I believe this should be `var result = results.Results.First();`

**Comment by UmaHarano** [comment]
Thanks for reporting this! This will be fixed in the next update of the docs.
