### ISSUE TITLE
GeometryEngine NearestPoint returns null in PointIndex

### ISSUE THREAD

**Issue by ibrahimkais** [Esri/arcgis-pro-sdk#27]
I'm trying to get the nearest point in a polyline for a point

`ProximityResult proximityResult = GeometryEngine.Instance.NearestPoint(polylineGeometry, mapPoint);`

but it returns null in the proximityResult.PointIndex although there is a point returned in the proximityResult

So I had to search for the index by this code
`List<MapPoint> points = polylineGeometry.Points.ToList();`
`int index = points.FindIndex(p => p.X == proximityResult.Point.X && p.Y == proximityResult.Point.Y);`

![GeometryEngine](https://user-images.githubusercontent.com/2798360/82003976-0a2e7680-9662-11ea-8577-b36e8a85b125.jpg)

I hope this could help.

**Comment by alocke** [comment]
Hi, 
The nearest point might not be a vertex in the geometry. If your input geometry is not a point or multipoint, then ProximityResult.PointIndex is null and ProximityResult.SegmentIndex is the segment which contains the nearest point. 
See https://pro.arcgis.com/en/pro-app/sdk/api-reference/#topic8269.html

If you want the nearest vertex, then use GeometryEngine.NearestVertex. 
You can read about it here: https://pro.arcgis.com/en/pro-app/sdk/api-reference/#topic8271.html

Let me know if you have any questions. 
Annette
