### ISSUE TITLE
Template doesn't appear in visual studio 2015

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-pro-sdk#4]
Hello, Please bear with me as I'm new to visual studio and the sdk. 

I've tried following the steps to install the sdk to visual studio but when I get to the create new project step, I am unable to proceed becasue the template is not listed. 

![image](https://cloud.githubusercontent.com/assets/5471079/18204850/8b65138c-70e4-11e6-98f9-665a2e6989ac.png)

**Comment by dvimster** [comment]
Try this ![image](https://cloud.githubusercontent.com/assets/11092103/18930071/4e3f1732-85cf-11e6-8e9d-c291663f5e9e.png)
