### ISSUE TITLE
No Project Types visible after installing ArcGIS Pro SDK thru Extensions and Updates

### ISSUE THREAD

**Issue by trippetoe** [Esri/arcgis-pro-sdk#6]
After following the process outlined here (https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Installation-and-Upgrade#install-from-within-visual-studio), I don't see a project type available under the ArcGIS Pro Add-Ins templates. I tried changing the .NET Framework selections and that didn't seem to make any difference. 

I am using VS Professional 2015 

![image](https://cloud.githubusercontent.com/assets/22507276/24226190/44847ac0-0f22-11e7-891e-29b2272a20b2.png)

**Comment by Wolf-K** [comment]
You need to select a 'required' .Net Framework.  I think it has to be at least 4.6.1, you can see it in the requirements section of our documentation.

**Comment by trippetoe** [comment]
Thanks for the tip. Once i selected ".NET Framework 4.6.1", i see the expected project types. Thank you.

I reviewed the Git Hub document at https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Installation-and-Upgrade#install-from-within-visual-studio, and i did not find any reference to requirements around the .NET framework (perhaps i missed it?).  The doc's screenshots show that '.NET Framework' has been selected and not a specific version. Perhaps you guys could add info about the .NET requirement to the document?

![image](https://cloud.githubusercontent.com/assets/22507276/24262231/b9b5de8a-0fb6-11e7-886b-d7121559546a.png)

**Comment by Wolf-K** [comment]
It's specific under requirements in a lot a places, however, GitHub's markdown is currently not working as before to a lot of our GitHub links are not working.  Here are the requirements off our landing page (scroll down to supported platforms):
[http://pro.arcgis.com/en/pro-app/get-started/arcgis-pro-system-requirements.htm](http://pro.arcgis.com/en/pro-app/get-started/arcgis-pro-system-requirements.htm)
