### ISSUE TITLE
wiki page images are broken

### ISSUE THREAD

**Issue by mhogeweg** [Esri/arcgis-pro-sdk#7]
there are some wiki pages with broken references to images:
https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Build-Your-First-Add-in

instead of the image this shows:

```
![New Project](http://Esri.github.io/arcgis-pro-sdk/images/How to Build an Add-in with the ArcGIS Pro SDK for .NET/new-project.png "New Project")
```

escaping the spaces in the URL resolves this:
```
http://Esri.github.io/arcgis-pro-sdk/images/How%20to%20Build%20an%20Add-in%20with%20the%20ArcGIS%20Pro%20SDK%20for%20.NET/new-project.png
```

![New Project](http://Esri.github.io/arcgis-pro-sdk/images/How%20to%20Build%20an%20Add-in%20with%20the%20ArcGIS%20Pro%20SDK%20for%20.NET/new-project.png "New Project")

**Comment by Wolf-K** [comment]
Thanks for pointing this out.  GitHub apparently switched to a different markdown engine which is not compatible with the one they used until a few weeks back.  We will update all of our content over the next weeks to work with their new markdown engine (unfortunately we have hundreds of wiki pages so this will take some time).
