### ISSUE TITLE
topic links incorrectly formatted in proconcepts geodatabase page.

### ISSUE THREAD

**Issue by SoJourned** [Esri/arcgis-pro-sdk#8]
The anchor links for topics are incorrectly formatted in the proconcepts geodatabase page.
https://github.com/esri/arcgis-pro-sdk/wiki/ProConcepts-Geodatabase
e.g. The topics appear as.
Datastore
[Geodatabase] (#geodatabase)
[QueryDef] (#querydef) 

Most of the links in the text also appear incorrect.

**Comment by arcgisprosdk** [comment]
Fixed now.
